# Generated by Django 5.2.5 on 2025-09-11 03:23

from django.db import migrations
from decimal import Decimal


def create_default_plans(apps, schema_editor):
    SubscriptionPlan = apps.get_model('payments', 'SubscriptionPlan')
    
    # Create trial plan
    SubscriptionPlan.objects.create(
        name='Trial Plan',
        plan_type='trial',
        price=Decimal('0.00'),
        duration_days=14,
        description='Free trial plan for 14 days'
    )
    
    # Create standard plan
    SubscriptionPlan.objects.create(
        name='Standard Plan',
        plan_type='standard',
        price=Decimal('99.99'),
        duration_days=30,
        description='Standard monthly plan'
    )


def remove_default_plans(apps, schema_editor):
    SubscriptionPlan = apps.get_model('payments', 'SubscriptionPlan')
    SubscriptionPlan.objects.filter(name__in=['Trial Plan', 'Standard Plan']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_plans, remove_default_plans),
    ]
