# Generated by Django 5.2.5 on 2025-10-21 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='conversation',
            new_name='chat_conver_hotel_i_f842bc_idx',
            old_name='chat_conver_hotel_i_f1e0be_idx',
        ),
        migrations.AlterField(
            model_name='conversation',
            name='department',
            field=models.CharField(choices=[('Reception', 'Reception'), ('Housekeeping', 'Housekeeping'), ('Room Service', 'Room Service'), ('Café', 'Café'), ('Management', 'Management')], default='Reception', max_length=20),
        ),
    ]
