# Generated by Django 5.2.5 on 2025-10-21 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_rename_chat_conver_hotel_i_f1e0be_idx_chat_conver_hotel_i_f842bc_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='department',
            field=models.CharField(choices=[('Reception', 'Reception'), ('Housekeeping', 'Housekeeping'), ('Room Service', 'Room Service'), ('Restaurant', 'Restaurant'), ('Management', 'Management')], default='Reception', max_length=20),
        ),
    ]
