# Generated by Django 5.2.5 on 2025-10-22 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_conversation_department'),
        ('guest', '0011_guestidentitydocument_document_file_back_and_more'),
        ('hotel', '0019_delete_department'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='conversation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='conversation',
            name='conversation_type',
            field=models.CharField(choices=[('service', 'Service'), ('demo', 'Demo'), ('checkin', 'Check-in'), ('checked_in', 'Checked In'), ('general', 'General')], default='general', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='conversation',
            unique_together={('guest', 'hotel', 'department', 'conversation_type', 'status')},
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['hotel', 'conversation_type', 'status'], name='chat_conver_hotel_i_301c78_idx'),
        ),
    ]
