# Generated by Django 5.2.5 on 2025-10-24 11:05

import lobbybee.utils.file_url
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_conversation_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to=lobbybee.utils.file_url.upload_to_chat_media),
        ),
    ]
