# Generated by Django 5.2.5 on 2025-10-24 16:58

import django.db.models.deletion
import lobbybee.utils.file_url
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_message_media_file'),
        ('hotel', '0019_delete_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('template_type', models.CharField(choices=[('greeting', 'Greeting'), ('checkin', 'Check-in'), ('service', 'Service Request'), ('farewell', 'Farewell'), ('emergency', 'Emergency'), ('promotion', 'Promotion'), ('general', 'General')], max_length=20)),
                ('text_content', models.TextField()),
                ('media_file', models.FileField(blank=True, null=True, upload_to=lobbybee.utils.file_url.upload_to_chat_media)),
                ('media_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('is_customizable', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('variables', models.JSONField(blank=True, default=list, help_text='List of variable names that can be customized')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['template_type', 'is_active'], name='chat_messag_templat_bb9335_idx'), models.Index(fields=['name'], name='chat_messag_name_deb08a_idx')],
            },
        ),
        migrations.CreateModel(
            name='CustomMessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('template_type', models.CharField(choices=[('greeting', 'Greeting'), ('checkin', 'Check-in'), ('service', 'Service Request'), ('farewell', 'Farewell'), ('emergency', 'Emergency'), ('promotion', 'Promotion'), ('general', 'General')], max_length=20)),
                ('text_content', models.TextField()),
                ('media_file', models.FileField(blank=True, null=True, upload_to=lobbybee.utils.file_url.upload_to_chat_media)),
                ('media_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('is_customizable', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('variables', models.JSONField(blank=True, default=list, help_text='List of variable names that can be customized')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_templates', to='hotel.hotel')),
                ('base_template', models.ForeignKey(blank=True, help_text='Base template this customization is derived from', null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.messagetemplate')),
            ],
            options={
                'indexes': [models.Index(fields=['hotel', 'template_type', 'is_active'], name='chat_custom_hotel_i_989537_idx'), models.Index(fields=['hotel', 'name'], name='chat_custom_hotel_i_edd9bd_idx')],
                'unique_together': {('hotel', 'name')},
            },
        ),
    ]
