# Generated by Django 5.2.5 on 2025-10-24 17:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_messagetemplate_custommessagetemplate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='flow_id',
            field=models.CharField(blank=True, help_text="Identifier for the flow (e.g., 'checkin', 'service_request')", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='flow_step',
            field=models.IntegerField(blank=True, help_text='Current step number in the flow', null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='is_flow',
            field=models.BooleanField(default=False, help_text='Whether this message is part of a hardcoded flow'),
        ),
        migrations.AddField(
            model_name='message',
            name='is_flow_step_success',
            field=models.BooleanField(blank=True, help_text='Whether this flow step was successful', null=True),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['is_flow', 'flow_id'], name='chat_messag_is_flow_f70213_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['flow_id', 'flow_step'], name='chat_messag_flow_id_530f3a_idx'),
        ),
    ]
