# Generated by Django 5.2.5 on 2025-10-24 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_message_flow_id_message_flow_step_message_is_flow_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('document', 'Document'), ('video', 'Video'), ('audio', 'Audio'), ('system', 'System')], default='text', max_length=20),
        ),
    ]
