# Generated by Django 5.2.5 on 2025-11-02 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_alter_message_message_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='fulfilled_at',
            field=models.DateTimeField(blank=True, help_text='When the request was marked as fulfilled', null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='fulfillment_notes',
            field=models.TextField(blank=True, help_text='Notes about request fulfillment status', null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='is_request_fulfilled',
            field=models.BooleanField(default=False, help_text="Whether the guest's request was successfully fulfilled"),
        ),
    ]
