# Generated by Django 5.2.5 on 2025-11-06 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_add_whatsapp_message_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook_type', models.CharField(choices=[('guest', 'Guest Webhook'), ('flow', 'Flow Webhook'), ('outgoing', 'Outgoing Message')], max_length=20)),
                ('whatsapp_message_id', models.CharField(db_index=True, max_length=100)),
                ('whatsapp_number', models.CharField(db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('validation_failed', 'Validation Failed'), ('processing_failed', 'Processing Failed'), ('duplicate', 'Duplicate')], default='pending', max_length=20)),
                ('request_data', models.JSONField(blank=True, default=dict)),
                ('response_data', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('processing_time_ms', models.IntegerField(blank=True, null=True)),
                ('message_id', models.IntegerField(blank=True, help_text='Created message ID if successful', null=True)),
                ('conversation_id', models.IntegerField(blank=True, help_text='Related conversation ID', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['webhook_type', 'status'], name='chat_webhoo_webhook_f1d3eb_idx'), models.Index(fields=['whatsapp_number', 'created_at'], name='chat_webhoo_whatsap_e8ac61_idx'), models.Index(fields=['created_at'], name='chat_webhoo_created_0a7ab6_idx')],
                'unique_together': {('webhook_type', 'whatsapp_message_id')},
            },
        ),
    ]
