# Generated by Django 5.2.5 on 2025-11-06 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_webhookattempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='whatsapp_message_id',
            field=models.CharField(blank=True, db_index=True, help_text='WhatsApp message ID for deduplication of incoming guest messages only', max_length=100, null=True),
        ),
    ]
