# Generated by Django 5.2.5 on 2025-11-07 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_auto_20251106_1118'),
        ('guest', '0011_guestidentitydocument_document_file_back_and_more'),
        ('hotel', '0022_remove_wifi_password_from_hotel'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='conversation',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('guest', 'hotel', 'department', 'conversation_type'), name='unique_active_conversation'),
        ),
    ]
