# Generated by Django 5.2.5 on 2025-11-14 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_update_conversation_unique_constraint'),
        ('guest', '0013_booking_is_via_whatsapp'),
        ('hotel', '0022_remove_wifi_password_from_hotel'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='conversation',
            name='unique_active_conversation',
        ),
        migrations.AlterField(
            model_name='conversation',
            name='guest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='guest.guest'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='hotel.hotel'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active'), ('guest__isnull', False), ('hotel__isnull', False)), fields=('guest', 'hotel', 'department', 'conversation_type'), name='unique_active_conversation'),
        ),
    ]
