# Generated by Django 5.2.5 on 2025-11-14

from django.db import migrations


def create_starter_templates(apps, schema_editor):
    """
    Create starter message templates for LobbyBee hotel CRM platform.
    These are global templates that can be used across all hotels.
    """
    MessageTemplate = apps.get_model('chat', 'MessageTemplate')
    
    # Define starter templates with unique names for code reference
    starter_templates = [
        {
            'name': 'lobbybee_app_start',
            'template_type': 'greeting',
            'text_content': 'Hello! Welcome to LobbyBee, your hotel CRM assistant. I\'m here to help streamline your guest interactions. How can I assist you today? Visit us at https://lobbybee.com for more information.',
            'variables': [],
            'description': 'Initial app start message when users first interact with LobbyBee platform',
            'is_customizable': False,
            'is_active': True,
        },
        {
            'name': 'lobbybee_hotel_welcome',
            'template_type': 'greeting',
            'text_content': 'Hello {{guest_name}}! Welcome to {{hotel_name}}! We are delighted to have you stay with us. Your room {{room_number}} is ready, and our team is here to ensure you have a comfortable and pleasant stay. Feel free to reach out if you need anything during your visit.',
            'variables': ['guest_name', 'hotel_name', 'room_number'],
            'description': 'Hotel welcome message for new guests upon check-in',
            'is_customizable': True,
            'is_active': True,
        },
        {
            'name': 'lobbybee_checkout_thank_you',
            'template_type': 'farewell',
            'text_content': 'Dear {{guest_name}}, thank you for choosing {{hotel_name}} for your stay! We hope you had a wonderful experience. Safe travels, and we look forward to welcoming you back soon. Don\'t forget to share your feedback with us!',
            'variables': ['guest_name', 'hotel_name'],
            'description': 'Thank you message for guests upon check-out',
            'is_customizable': True,
            'is_active': True,
        },
        {
            'name': 'lobbybee_breakfast_reminder',
            'template_type': 'service',
            'text_content': 'Good morning {{guest_name}}! Breakfast is being served at our restaurant from {{breakfast_time}}. Start your day with our delicious spread of local and international cuisine. Have a wonderful day ahead!',
            'variables': ['guest_name', 'breakfast_time'],
            'description': 'Breakfast service reminder for hotel guests',
            'is_customizable': True,
            'is_active': True,
        },
        {
            'name': 'lobbybee_lunch_reminder',
            'template_type': 'service',
            'text_content': 'Hello {{guest_name}}! Lunch is now being served at our restaurant. Enjoy our special lunch menu featuring fresh, locally sourced ingredients. Visit us between {{lunch_start_time}} and {{lunch_end_time}}.',
            'variables': ['guest_name', 'lunch_start_time', 'lunch_end_time'],
            'description': 'Lunch service reminder for hotel guests',
            'is_customizable': True,
            'is_active': True,
        },
        {
            'name': 'lobbybee_dinner_reminder',
            'template_type': 'service',
            'text_content': 'Good evening {{guest_name}}! Dinner is being served at our restaurant tonight. Join us for an exquisite dining experience with our chef\'s special menu. We\'re open from {{dinner_start_time}} to {{dinner_end_time}}.',
            'variables': ['guest_name', 'dinner_start_time', 'dinner_end_time'],
            'description': 'Dinner service reminder for hotel guests',
            'is_customizable': True,
            'is_active': True,
        },
        {
            'name': 'lobbybee_checkout_reminder',
            'template_type': 'farewell',
            'text_content': 'Dear {{guest_name}}, this is a friendly reminder that your check-out time is today at {{checkout_time}}. Please settle any outstanding charges and return your room keys. We hope you enjoyed your stay at {{hotel_name}}! Safe travels!',
            'variables': ['guest_name', 'checkout_time', 'hotel_name'],
            'description': 'Check-out reminder for guests on their departure day',
            'is_customizable': True,
            'is_active': True,
        },
        {
            'name': 'lobbybee_platform_contact',
            'template_type': 'general',
            'text_content': 'Hello! For technical support or inquiries about LobbyBee services, please contact our support team:\n\n📱 Phone: 7736600773\n🌐 Website: https://lobbybee.com\n\nWe are here to help you make the most of your hotel CRM experience. Our team is available 24/7 to assist you with any questions or issues.',
            'variables': [],
            'description': 'Platform contact and support information template',
            'is_customizable': False,
            'is_active': True,
        },
    ]
    
    # Create each template
    for template_data in starter_templates:
        MessageTemplate.objects.get_or_create(
            name=template_data['name'],
            defaults=template_data
        )


def remove_starter_templates(apps, schema_editor):
    """
    Remove starter message templates.
    """
    MessageTemplate = apps.get_model('chat', 'MessageTemplate')
    
    starter_template_names = [
        'lobbybee_app_start',
        'lobbybee_hotel_welcome',
        'lobbybee_checkout_thank_you',
        'lobbybee_breakfast_reminder',
        'lobbybee_lunch_reminder',
        'lobbybee_dinner_reminder',
        'lobbybee_checkout_reminder',
        'lobbybee_platform_contact',
    ]
    
    MessageTemplate.objects.filter(name__in=starter_template_names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_remove_conversation_unique_active_conversation_and_more'),
    ]

    operations = [
        migrations.RunPython(create_starter_templates, remove_starter_templates),
    ]