# Generated by Django 5.2.5 on 2025-11-27 05:18

import lobbybee.utils.file_url
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_add_starter_message_templates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custommessagetemplate',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to=lobbybee.utils.file_url.upload_to_custom_template_media),
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to=lobbybee.utils.file_url.upload_to_template_media),
        ),
    ]
