# Generated by Django 5.2.5 on 2025-11-29 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0016_alter_custommessagetemplate_media_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='conversation_type',
            field=models.CharField(choices=[('service', 'Service'), ('demo', 'Demo'), ('checkin', 'Check-in'), ('checked_in', 'Checked In'), ('general', 'General'), ('feedback', 'Feedback')], default='general', max_length=20),
        ),
    ]
