# Generated by Django 5.2.5 on 2025-09-22 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0010_stay_register_number'),
        ('message_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='stay',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='guest.stay'),
        ),
    ]
