# Generated by Django 5.2.5 on 2025-10-17 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message_manager', '0002_conversation_id_alter_conversation_stay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='department',
        ),
        migrations.RemoveField(
            model_name='messagetemplate',
            name='department',
        ),
    ]
