# Generated by Django 5.2.5 on 2025-10-18 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_manager', '0003_remove_conversation_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='department',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
