# Generated by Django 5.2.5 on 2025-10-18 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_manager', '0004_conversation_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='department',
            field=models.CharField(blank=True, choices=[('Reception', 'Reception'), ('Housekeeping', 'Housekeeping'), ('Room Service', 'Room Service'), ('Café', 'Café'), ('Management', 'Management')], max_length=20, null=True),
        ),
    ]
