# Generated by Django 5.2.4 on 2025-08-13 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotel', '0013_room_hotel_room_hotel_i_74f710_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_id', models.CharField(max_length=100, unique=True)),
                ('flow_type', models.CharField(max_length=50)),
                ('message_template', models.TextField()),
                ('options', models.JSONField(blank=True, default=dict)),
                ('conditional_next_steps', models.JSONField(blank=True, null=True)),
                ('is_optional', models.BooleanField(default=False)),
                ('next_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_next', to='context_manager.flowstep')),
                ('previous_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_previous', to='context_manager.flowstep')),
            ],
        ),
        migrations.CreateModel(
            name='MessageQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20)),
                ('message_type', models.CharField(max_length=50)),
                ('message_content', models.TextField()),
                ('scheduled_time', models.DateTimeField(db_index=True)),
                ('sent_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('retry_count', models.IntegerField(default=0)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledMessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(max_length=50)),
                ('trigger_condition', models.JSONField()),
                ('message_template', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_templates', to='hotel.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='ConversationContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20)),
                ('context_data', models.JSONField(default=dict)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel')),
            ],
            options={
                'indexes': [models.Index(fields=['user_id', 'hotel'], name='context_man_user_id_c2e8a9_idx')],
                'unique_together': {('user_id', 'hotel')},
            },
        ),
    ]
