# Generated by Django 5.2.5 on 2025-08-17 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotel', '0013_room_hotel_room_hotel_i_74f710_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('action_type', models.CharField(max_length=50)),
                ('configuration', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='FlowTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('payload', models.JSONField()),
                ('processed_successfully', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConversationContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20)),
                ('context_data', models.JSONField(default=dict)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('navigation_stack', models.JSONField(default=list)),
                ('flow_expires_at', models.DateTimeField(null=True)),
                ('last_guest_message_at', models.DateTimeField(null=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='ConversationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_content', models.TextField()),
                ('is_from_guest', models.BooleanField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='context_manager.conversationcontext')),
            ],
        ),
        migrations.CreateModel(
            name='FlowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_id', models.CharField(max_length=100)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel')),
            ],
        ),
        migrations.AddField(
            model_name='conversationcontext',
            name='current_step',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='context_manager.flowstep'),
        ),
        migrations.CreateModel(
            name='FlowStepTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_name', models.CharField(max_length=100)),
                ('message_template', models.TextField()),
                ('message_type', models.CharField(max_length=50)),
                ('options', models.JSONField(default=dict)),
                ('conditional_next_steps', models.JSONField(blank=True, null=True)),
                ('actions', models.ManyToManyField(blank=True, to='context_manager.flowaction')),
                ('next_step_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='context_manager.flowsteptemplate')),
                ('flow_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='context_manager.flowtemplate')),
            ],
        ),
        migrations.AddField(
            model_name='flowstep',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='context_manager.flowsteptemplate'),
        ),
        migrations.CreateModel(
            name='HotelFlowConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('customization_data', models.JSONField(default=dict)),
                ('flow_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='context_manager.flowtemplate')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='MessageQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20)),
                ('message_type', models.CharField(max_length=50)),
                ('message_content', models.TextField()),
                ('scheduled_time', models.DateTimeField(db_index=True)),
                ('sent_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('on_hold', 'On Hold')], db_index=True, default='pending', max_length=20)),
                ('retry_count', models.IntegerField(default=0)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledMessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(max_length=50)),
                ('trigger_condition', models.JSONField()),
                ('message_template', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_templates', to='hotel.hotel')),
            ],
        ),
        migrations.AddIndex(
            model_name='conversationcontext',
            index=models.Index(fields=['user_id', 'hotel'], name='context_man_user_id_c2e8a9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='conversationcontext',
            unique_together={('user_id', 'hotel')},
        ),
        migrations.AlterUniqueTogether(
            name='flowstep',
            unique_together={('template', 'hotel')},
        ),
        migrations.AlterUniqueTogether(
            name='hotelflowconfiguration',
            unique_together={('hotel', 'flow_template')},
        ),
    ]
