# Generated by Django 5.2.4 on 2025-08-13 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('context_manager', '0001_initial'),
    ]

    operations = [
    ]
