# Generated by Django 5.2.5 on 2025-08-18 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Placeholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="The placeholder name, e.g., 'guest_name'", max_length=50, unique=True)),
                ('description', models.TextField(help_text='A description of what the placeholder represents.')),
                ('resolving_logic', models.CharField(help_text="The logic to resolve the placeholder, e.g., 'guest.full_name'", max_length=200)),
            ],
        ),
    ]
