# Generated by Django 5.2.4 on 2025-08-13 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context_manager', '0002_seed_checkin_flow_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowstep',
            name='is_hotel_customizable',
            field=models.BooleanField(default=True, help_text='If True, hotels can customize this flow step. If False, only platform admins can modify it.'),
        ),
    ]
