# Generated by Django 5.2.5 on 2025-08-18 06:55

from django.db import migrations


def forwards_func(apps, schema_editor):
    Placeholder = apps.get_model("context_manager", "Placeholder")
    placeholders = [
        {'name': 'guest_id', 'description': 'The unique ID of the guest', 'resolving_logic': 'guest.id'},
        {'name': 'guest_name', 'description': 'The full name of the guest', 'resolving_logic': 'guest.full_name'},
        {'name': 'guest_email', 'description': 'The email address of the guest', 'resolving_logic': 'guest.email'},
        {'name': 'guest_nationality', 'description': 'The nationality of the guest', 'resolving_logic': 'guest.nationality'},
        {'name': 'loyalty_points', 'description': 'The loyalty points of the guest', 'resolving_logic': 'guest.loyalty_points'},
        {'name': 'hotel_name', 'description': 'The name of the hotel', 'resolving_logic': 'hotel.name'},
        {'name': 'wifi_password', 'description': 'The Wi-Fi password of the hotel', 'resolving_logic': 'hotel.wifi_password'},
        {'name': 'room_number', 'description': 'The room number of the guest\'s stay', 'resolving_logic': 'stay.room.room_number'},
        {'name': 'checkin_time', 'description': 'The check-in time of the guest\'s stay', 'resolving_logic': 'stay.check_in_date'},
        {'name': 'checkout_time', 'description': 'The check-out time of the guest\'s stay', 'resolving_logic': 'stay.check_out_date'},
    ]
    for placeholder_data in placeholders:
        Placeholder.objects.create(**placeholder_data)

def reverse_func(apps, schema_editor):
    Placeholder = apps.get_model("context_manager", "Placeholder")
    Placeholder.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('context_manager', '0002_placeholder'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]