# Generated by Django 5.2.4 on 2025-08-14 10:15

from django.db import migrations
from django.utils import timezone

def create_initial_flow_steps(apps, schema_editor):
    FlowStep = apps.get_model('context_manager', 'FlowStep')
    
    # Create the initial start step for QR code flow
    FlowStep.objects.get_or_create(
        step_id='initial_start',
        defaults={
            'flow_type': 'guest_checkin',
            'message_template': 'Welcome to {hotel_name}! Please provide your full name to begin the check-in process.',
            'options': {},
            'is_optional': False,
            'is_hotel_customizable': True
        }
    )
    
    # Create the step for collecting guest details
    FlowStep.objects.get_or_create(
        step_id='collect_guest_details',
        defaults={
            'flow_type': 'guest_checkin',
            'message_template': 'Thank you, {guest_name}! Please provide the following details:\n1. Your email address\n2. Your nationality\n3. Your expected check-in date (DD-MM-YYYY)',
            'options': {},
            'is_optional': False,
            'is_hotel_customizable': True
        }
    )
    
    # Create the step for matching or creating a stay
    FlowStep.objects.get_or_create(
        step_id='match_or_create_stay',
        defaults={
            'flow_type': 'guest_checkin',
            'message_template': 'Thank you for providing your details. Please wait while we look up your reservation.',
            'options': {},
            'is_optional': False,
            'is_hotel_customizable': False  # This is an internal step, not customizable
        }
    )

def reverse_flow_steps(apps, schema_editor):
    FlowStep = apps.get_model('context_manager', 'FlowStep')
    
    # Remove the flow steps we created
    FlowStep.objects.filter(step_id__in=[
        'initial_start',
        'collect_guest_details',
        'match_or_create_stay'
    ]).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('context_manager', '0003_flowstep_is_hotel_customizable'),
    ]

    operations = [
        migrations.RunPython(create_initial_flow_steps, reverse_flow_steps),
    ]