# Generated by Django 5.2.5 on 2025-08-18 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context_manager', '0003_seed_placeholders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowsteptemplate',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('media', 'Media'), ('quick-reply', 'Quick Reply'), ('list-picker', 'List Picker'), ('call-to-action', 'Call to Action'), ('template', 'Template')], default='text', max_length=50),
        ),
    ]
