# Generated by Django 5.2.4 on 2025-08-14 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context_manager', '0004_add_qr_code_flow_steps'),
        ('hotel', '0013_room_hotel_room_hotel_i_74f710_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowstep',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel'),
        ),
        migrations.AlterField(
            model_name='flowstep',
            name='is_hotel_customizable',
            field=models.BooleanField(default=True),
        ),
    ]
