# Generated by Django 5.2.5 on 2025-08-21 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('context_manager', '0004_alter_flowsteptemplate_message_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversationcontext',
            name='flow_expires_at',
        ),
    ]
