# Generated by Django 5.2.5 on 2025-08-16 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context_manager', '0005_add_hotel_field_to_flowstep'),
        ('hotel', '0013_room_hotel_room_hotel_i_74f710_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('action_type', models.CharField(max_length=50)),
                ('configuration', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='FlowTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('payload', models.JSONField()),
                ('processed_successfully', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='conversationcontext',
            name='current_step',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='context_manager.flowstep'),
        ),
        migrations.AddField(
            model_name='conversationcontext',
            name='flow_expires_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='conversationcontext',
            name='last_guest_message_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='conversationcontext',
            name='navigation_stack',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='messagequeue',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('on_hold', 'On Hold')], db_index=True, default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='ConversationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_content', models.TextField()),
                ('is_from_guest', models.BooleanField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='context_manager.conversationcontext')),
            ],
        ),
        migrations.CreateModel(
            name='FlowStepTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_name', models.CharField(max_length=100)),
                ('message_template', models.TextField()),
                ('message_type', models.CharField(max_length=50)),
                ('options', models.JSONField(default=dict)),
                ('conditional_next_steps', models.JSONField(blank=True, null=True)),
                ('actions', models.ManyToManyField(blank=True, to='context_manager.flowaction')),
                ('next_step_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='context_manager.flowsteptemplate')),
                ('flow_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='context_manager.flowtemplate')),
            ],
        ),
        migrations.CreateModel(
            name='HotelFlowConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('customization_data', models.JSONField(default=dict)),
                ('flow_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='context_manager.flowtemplate')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel')),
            ],
            options={
                'unique_together': {('hotel', 'flow_template')},
            },
        ),
    ]
