# Generated by Django 5.2.5 on 2025-08-21 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context_manager', '0005_remove_conversationcontext_flow_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationcontext',
            name='error_count',
            field=models.IntegerField(default=0),
        ),
    ]
