# Generated by Django 5.2.5 on 2025-08-22 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context_manager', '0006_conversationcontext_error_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowsteptemplate',
            name='allowed_flow_categories',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='flowsteptemplate',
            name='quick_reply_navigation',
            field=models.JSONField(blank=True, default=dict, help_text="e.g., {'Back': 'back', 'Main Menu': 'main_menu'}"),
        ),
        migrations.AlterField(
            model_name='conversationcontext',
            name='current_step',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='context_manager.flowstep'),
        ),
    ]
