# Generated by Django 5.2.5 on 2025-08-22 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context_manager', '0007_flowsteptemplate_allowed_flow_categories_and_more'),
        ('hotel', '0015_alter_hotel_address_alter_hotel_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationcontext',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel'),
        ),
    ]
