# Generated by Django 5.2.5 on 2025-08-22 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context_manager', '0008_alter_conversationcontext_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowsteptemplate',
            name='order',
            field=models.IntegerField(default=0, help_text='Controls the display order of the step in a flow.'),
        ),
        migrations.AlterField(
            model_name='flowsteptemplate',
            name='flow_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_templates', to='context_manager.flowtemplate'),
        ),
    ]
