# Generated by Django 5.2.5 on 2025-08-23 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context_manager', '0009_flowsteptemplate_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationcontext',
            name='context_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='conversationcontext',
            name='navigation_stack',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='flowaction',
            name='configuration',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flowsteptemplate',
            name='allowed_flow_categories',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='flowsteptemplate',
            name='options',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='flowsteptemplate',
            name='quick_reply_navigation',
            field=models.JSONField(blank=True, default=dict, help_text="e.g., {'Back': 'back', 'Main Menu': 'main_menu'}", null=True),
        ),
        migrations.AlterField(
            model_name='hotelflowconfiguration',
            name='customization_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='scheduledmessagetemplate',
            name='trigger_condition',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='webhooklog',
            name='payload',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
