# Generated by Django 5.2.5 on 2025-08-23 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context_manager', '0010_alter_conversationcontext_context_data_and_more'),
        ('hotel', '0016_hotel_is_demo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowstep',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel'),
        ),
    ]
