# Generated by Django 5.2.5 on 2025-08-24 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context_manager', '0011_alter_flowstep_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowsteptemplate',
            name='message_template',
            field=models.JSONField(default=dict, help_text='The WhatsApp-compatible message object template.'),
        ),
    ]
