# Generated by Django 5.2.5 on 2025-08-28 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context_manager', '0012_alter_flowsteptemplate_message_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationmessage',
            name='message_type',
            field=models.CharField(default='text', help_text='Type of message: text, image, voice, etc.', max_length=20),
        ),
        migrations.AlterField(
            model_name='conversationmessage',
            name='context',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='context_manager.conversationcontext'),
        ),
    ]
