# Generated by Django 5.2.5 on 2025-08-29 15:11

import context_manager.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context_manager', '0013_conversationmessage_message_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsappMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('whatsapp_media_id', models.CharField(max_length=255, unique=True)),
                ('mime_type', models.CharField(max_length=100)),
                ('file_size', models.BigIntegerField()),
                ('file', models.FileField(upload_to=context_manager.models.upload_to_whatsapp_media)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='conversationmessage',
            name='media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='context_manager.whatsappmedia'),
        ),
    ]
