# Generated by Django 5.2.5 on 2025-08-29 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context_manager', '0014_whatsappmedia_conversationmessage_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowsteptemplate',
            name='should_store_media',
            field=models.BooleanField(default=False, help_text='If true, any incoming media for this step will be stored.'),
        ),
    ]
