# Generated by Django 5.2.5 on 2025-09-08 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context_manager', '0015_flowsteptemplate_should_store_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowstep',
            name='message_template',
            field=models.JSONField(blank=True, help_text='Custom message template for this hotel.', null=True),
        ),
        migrations.AddField(
            model_name='flowstep',
            name='message_type',
            field=models.CharField(blank=True, choices=[('text', 'Text'), ('media', 'Media'), ('quick-reply', 'Quick Reply'), ('list-picker', 'List Picker'), ('call-to-action', 'Call to Action'), ('template', 'Template')], help_text='Custom message type for this hotel.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='flowstep',
            name='options',
            field=models.JSONField(blank=True, help_text='Custom options for this hotel.', null=True),
        ),
        migrations.AddField(
            model_name='flowsteptemplate',
            name='is_customizable',
            field=models.BooleanField(default=True, help_text='If true, hotel admins can customize this step.'),
        ),
    ]
