# Generated by Django 5.2.5 on 2025-09-08 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('context_manager', '0016_flowstep_message_template_flowstep_message_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HotelFlowConfiguration',
        ),
    ]
