# Generated by Django 5.2.5 on 2025-09-08 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context_manager', '0017_delete_hotelflowconfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowsteptemplate',
            name='is_customizable',
            field=models.BooleanField(default=False, help_text='If true, hotel admins can customize this step.'),
        ),
    ]
