# Generated by Django 5.2.5 on 2025-09-09 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context_manager', '0018_alter_flowsteptemplate_is_customizable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappmedia',
            name='whatsapp_media_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
