# Generated by Django 5.2.5 on 2025-09-09 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context_manager', '0019_alter_whatsappmedia_whatsapp_media_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowstep',
            name='media',
            field=models.ForeignKey(blank=True, help_text="A hotel-specific media file to override the template's media.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='context_manager.whatsappmedia'),
        ),
        migrations.AddField(
            model_name='flowsteptemplate',
            name='media',
            field=models.ForeignKey(blank=True, help_text='An optional media file to be sent with this step.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='context_manager.whatsappmedia'),
        ),
    ]
