# Generated by Django 5.2.5 on 2025-12-13 02:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guest', '0016_stay_hours_24'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_reason', models.TextField(help_text='Internal reason for flagging (visible to platform staff only)')),
                ('global_note', models.TextField(blank=True, help_text='Public note visible to all hotels during check-in')),
                ('reset_reason', models.TextField(blank=True, help_text='Reason for resetting the flag')),
                ('flagged_by_police', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reset_at', models.DateTimeField(blank=True, null=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='guest.guest')),
                ('last_modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('reset_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reset_flags', to=settings.AUTH_USER_MODEL)),
                ('stay', models.ForeignKey(blank=True, help_text='Stay associated with the flag (null for platform flags)', null=True, on_delete=django.db.models.deletion.CASCADE, to='guest.stay')),
            ],
            options={
                'verbose_name': 'Guest Flag',
                'verbose_name_plural': 'Guest Flags',
                'indexes': [models.Index(fields=['guest', 'is_active'], name='flag_system_guest_i_0c985f_idx'), models.Index(fields=['stay'], name='flag_system_stay_id_c0f121_idx'), models.Index(fields=['flagged_by_police'], name='flag_system_flagged_e32ec2_idx'), models.Index(fields=['created_at'], name='flag_system_created_328abb_idx')],
            },
        ),
    ]
