# Generated by Django 5.2.4 on 2025-07-22 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_remove_hotel_admin_email_hotel_admin'),
    ]

    operations = [
    ]
