# Generated by Django 5.2.4 on 2025-07-22 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_auto_20250722_0640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='invited_by',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='verified_by',
        ),
        migrations.AddField(
            model_name='hotel',
            name='registration_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('suspended', 'Suspended'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='HotelStaff',
        ),
    ]
