# Generated by Django 5.2.4 on 2025-07-29 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_remove_hotel_admin_remove_hotel_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='timezone',
        ),
        migrations.AddField(
            model_name='hotel',
            name='time_zone',
            field=models.CharField(default='UTC', max_length=50),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='registration_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
