# Generated by Django 5.2.4 on 2025-08-04 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_remove_hotel_timezone_hotel_time_zone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
