# Generated by Django 5.2.4 on 2025-08-05 06:39

import django.db.models.deletion
import lobbybee.utils.file_url
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_hotel_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('license', 'Business License'), ('registration', 'Company Registration'), ('other', 'Other')], max_length=20)),
                ('document_file', models.FileField(upload_to=lobbybee.utils.file_url.upload_to_hotel_documents)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='hotel.hotel')),
            ],
        ),
    ]
