# Generated by Django 5.2.4 on 2025-08-11 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0001_initial'),
        ('hotel', '0010_roomcategory_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='current_guest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='guest.guest'),
        ),
    ]
