# Generated by Django 5.2.4 on 2025-08-11 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0011_room_current_guest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department_type', models.CharField(choices=[('reception', 'Reception'), ('housekeeping', 'Housekeeping'), ('room_service', 'Room Service'), ('maintenance', 'Maintenance'), ('concierge', 'Concierge'), ('restaurant', 'Restaurant'), ('spa', 'Spa & Wellness'), ('laundry', 'Laundry'), ('transport', 'Transport'), ('other', 'Other')], max_length=20)),
                ('whatsapp_number', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('whatsapp_number2', models.CharField(blank=True, max_length=15, null=True)),
                ('whatsapp_number3', models.CharField(blank=True, max_length=15, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('operating_hours_start', models.TimeField()),
                ('operating_hours_end', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='hotel.hotel')),
            ],
            options={
                'unique_together': {('hotel', 'department_type')},
            },
        ),
    ]
