# Generated by Django 5.2.4 on 2025-08-13 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0003_guest_notes'),
        ('hotel', '0012_department'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['hotel', 'floor'], name='hotel_room_hotel_i_74f710_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['hotel', 'status'], name='hotel_room_hotel_i_90b608_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['hotel', 'category'], name='hotel_room_hotel_i_9e70c2_idx'),
        ),
    ]
