# Generated by Django 5.2.5 on 2025-08-17 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0013_room_hotel_room_hotel_i_74f710_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='license_document_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='registration_document_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
