# Generated by Django 5.2.5 on 2025-08-22 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0015_alter_hotel_address_alter_hotel_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
    ]
