# Generated by Django 5.2.5 on 2025-08-25 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0016_hotel_is_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='verification_notes',
            field=models.TextField(blank=True, help_text='Notes for verification process by platform admin.'),
        ),
    ]
