# Generated by Django 5.2.5 on 2025-08-26 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0017_hotel_verification_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='additional_documents',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='license_document_url',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='registration_document_url',
        ),
    ]
