# Generated by Django 5.2.5 on 2025-10-21 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_rename_chat_conver_hotel_i_f1e0be_idx_chat_conver_hotel_i_f842bc_idx_and_more'),
        ('hotel', '0018_remove_hotel_additional_documents_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
    ]
