# Generated by Django 5.2.5 on 2025-10-30 10:07

import django.db.models.deletion
import lobbybee.utils.file_url
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0019_delete_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentQRCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Name/Description of the QR code (e.g., 'UPI Payment', 'PhonePe', 'Google Pay')", max_length=100)),
                ('image', models.FileField(help_text='QR code image file', upload_to=lobbybee.utils.file_url.upload_to_hotel_documents)),
                ('upi_id', models.CharField(help_text='UPI ID associated with this QR code', max_length=100)),
                ('active', models.BooleanField(default=True, help_text='Whether this QR code is currently active for use')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_qr_codes', to='hotel.hotel')),
            ],
            options={
                'indexes': [models.Index(fields=['hotel', 'active'], name='hotel_payme_hotel_i_97a6bc_idx')],
            },
        ),
    ]
