# Generated by Django 5.2.5 on 2025-10-31 14:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0020_paymentqrcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='WiFiCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('floor', models.IntegerField(help_text='Floor number for these WiFi credentials')),
                ('network_name', models.CharField(help_text='WiFi network name (SSID)', max_length=100)),
                ('password', models.CharField(help_text='WiFi password for this floor/category', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether these WiFi credentials are currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wifi_credentials', to='hotel.hotel')),
                ('room_category', models.ForeignKey(blank=True, help_text='Room category for these credentials. If null, applies to all categories on this floor.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wifi_credentials', to='hotel.roomcategory')),
            ],
            options={
                'indexes': [models.Index(fields=['hotel', 'floor'], name='hotel_wific_hotel_i_069daf_idx'), models.Index(fields=['hotel', 'room_category'], name='hotel_wific_hotel_i_0a5430_idx'), models.Index(fields=['hotel', 'is_active'], name='hotel_wific_hotel_i_da1d56_idx')],
                'unique_together': {('hotel', 'floor', 'room_category')},
            },
        ),
    ]
