# Generated by Django 5.2.5 on 2025-10-31 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0021_create_wifi_credential_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='wifi_password',
        ),
    ]
