# Generated by Django 5.2.5 on 2025-11-27 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0022_remove_wifi_password_from_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='google_review_link',
            field=models.URLField(blank=True, help_text='Google Review link for the hotel'),
        ),
    ]
