# Generated by Django 5.2.5 on 2025-12-15 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0023_hotel_google_review_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='breakfast_reminder',
            field=models.BooleanField(default=False, help_text='Enable breakfast reminders for guests'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='dinner_reminder',
            field=models.BooleanField(default=False, help_text='Enable dinner reminders for guests'),
        ),
    ]
