# Generated by Django 5.2.5 on 2026-02-05 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0024_hotel_breakfast_reminder_hotel_dinner_reminder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.CharField(max_length=25),
        ),
    ]
