# Generated by Django 5.2.11 on 2026-02-25 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0025_increase_room_number_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='check_out_time',
            field=models.TimeField(default='11:00', help_text="Hotel's standard check-out time"),
        ),
    ]
