# Generated by Django 5.2.11 on 2026-02-26 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0026_hotel_check_out_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='breakfast_time',
            field=models.TimeField(blank=True, help_text='Time when breakfast is served (e.g. 07:30)', null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='dinner_time',
            field=models.TimeField(blank=True, help_text='Time when dinner is served (e.g. 19:00)', null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='google_map_link',
            field=models.URLField(blank=True, help_text='Google Maps link for the hotel'),
        ),
    ]
