# Generated by Django 5.2.11 on 2026-02-26 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0027_add_google_map_link_breakfast_dinner_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='lunch_time',
            field=models.TimeField(blank=True, help_text='Time when lunch is served (e.g. 12:30)', null=True),
        ),
    ]
