# Generated by Django 5.2.11 on 2026-04-26 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0028_add_lunch_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='lunch_reminder',
            field=models.BooleanField(default=False, help_text='Enable lunch reminders for guests'),
        ),
    ]
