# Generated by Django 5.2.11 on 2026-06-20 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0029_hotel_lunch_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='gst_slabs',
            field=models.JSONField(blank=True, default=list, help_text='GST tiers: [{id, max_rate, gst_value}]'),
        ),
    ]
