# Generated by Django 5.2.11 on 2026-06-20 02:57

import hotel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0030_hotel_gst_slabs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='gst_slabs',
            field=models.JSONField(blank=True, default=hotel.models.default_gst_slabs, help_text='GST tiers: [{id, max_rate, gst_value}]'),
        ),
    ]
