# Generated by Django 5.2.11 on 2026-06-20 03:09

import lobbybee.utils.file_url
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0031_alter_hotel_gst_slabs'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='logo',
            field=models.FileField(blank=True, help_text='Hotel logo (optional)', null=True, upload_to=lobbybee.utils.file_url.upload_to_hotel_logo),
        ),
    ]
