# Generated by Django 5.2.4 on 2025-08-11 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='register_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
