# Generated by Django 5.2.4 on 2025-08-13 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0002_guest_register_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
