# Generated by Django 5.2.5 on 2025-08-17 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0003_guest_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='loyalty_points',
            field=models.IntegerField(default=0),
        ),
    ]
