# Generated by Django 5.2.5 on 2025-08-17 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0004_guest_loyalty_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='whatsapp_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
