# Generated by Django 5.2.5 on 2025-08-26 11:53

import lobbybee.utils.file_url
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0005_alter_guest_whatsapp_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestidentitydocument',
            name='document_file',
            field=models.FileField(upload_to=lobbybee.utils.file_url.upload_to_guest_documents),
        ),
    ]
