# Generated by Django 5.2.5 on 2025-09-06 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0007_booking_stay_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestidentitydocument',
            name='is_accompanying_guest',
            field=models.BooleanField(default=False),
        ),
    ]
