# Generated by Django 5.2.5 on 2025-09-06 08:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0008_guestidentitydocument_is_accompanying_guest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='guestidentitydocument',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='guestidentitydocument',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('guest',), name='unique_primary_document_per_guest'),
        ),
    ]
