# Generated by Django 5.2.5 on 2025-09-13 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0009_alter_guestidentitydocument_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stay',
            name='register_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
