# Generated by Django 5.2.5 on 2025-10-13 07:00

import lobbybee.utils.file_url
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0010_stay_register_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestidentitydocument',
            name='document_file_back',
            field=models.FileField(blank=True, null=True, upload_to=lobbybee.utils.file_url.upload_to_guest_documents),
        ),
        migrations.AlterField(
            model_name='guestidentitydocument',
            name='document_type',
            field=models.CharField(choices=[('aadhar_id', 'AADHAR ID'), ('driving_license', 'Driving License'), ('national_id', 'National ID'), ('voter_id', 'Voter ID'), ('other', 'Other Government ID')], max_length=20),
        ),
    ]
