# Generated by Django 5.2.5 on 2025-11-14 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0011_guestidentitydocument_document_file_back_and_more'),
        ('hotel', '0022_remove_wifi_password_from_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stay',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stays', to='hotel.room'),
        ),
    ]
