# Generated by Django 5.2.5 on 2025-11-14 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0012_alter_stay_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_via_whatsapp',
            field=models.BooleanField(default=False),
        ),
    ]
