# Generated by Django 5.2.5 on 2025-11-27 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0013_booking_is_via_whatsapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(help_text='Rating from 1 to 5')),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='guest.guest')),
                ('stay', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='guest.stay')),
            ],
        ),
    ]
