# Generated by Django 5.2.5 on 2025-12-07 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0014_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='stay',
            name='internal_note',
            field=models.TextField(blank=True, help_text='Internal notes about the guest stay'),
        ),
        migrations.AddField(
            model_name='stay',
            name='internal_rating',
            field=models.IntegerField(blank=True, help_text='Internal rating from 1 to 5', null=True),
        ),
    ]
