# Generated by Django 5.2.5 on 2025-12-12 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0015_stay_internal_note_stay_internal_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='stay',
            name='hours_24',
            field=models.BooleanField(default=False, help_text='Indicates if this is a 24-hour stay'),
        ),
    ]
