# Generated by Django 5.2.5 on 2025-12-15 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0016_stay_hours_24'),
    ]

    operations = [
        migrations.AddField(
            model_name='stay',
            name='breakfast_reminder',
            field=models.BooleanField(default=False, help_text='Enable breakfast reminder for this stay'),
        ),
        migrations.AddField(
            model_name='stay',
            name='dinner_reminder',
            field=models.BooleanField(default=False, help_text='Enable dinner reminder for this stay'),
        ),
    ]
