# Generated by Django 5.2.11 on 2026-03-13 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0017_stay_breakfast_reminder_stay_dinner_reminder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stay',
            name='hours_24',
        ),
    ]
