# Generated by Django 5.2.11 on 2026-03-13 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0018_remove_stay_hours_24'),
    ]

    operations = [
        migrations.AddField(
            model_name='stay',
            name='lunch_reminder',
            field=models.BooleanField(default=False, help_text='Enable lunch reminder for this stay'),
        ),
        migrations.CreateModel(
            name='ReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('checkout', 'Checkout'), ('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner')], max_length=20)),
                ('reminder_date', models.DateField()),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('sent', 'Sent'), ('skipped', 'Skipped'), ('failed', 'Failed')], default='scheduled', max_length=20)),
                ('reason', models.TextField(blank=True, null=True)),
                ('is_test', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_logs', to='guest.stay')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'reminder_type', 'reminder_date'], name='guest_remin_status_374aa1_idx')],
                'constraints': [models.UniqueConstraint(fields=('stay', 'reminder_type', 'reminder_date'), name='unique_stay_reminder_type_date')],
            },
        ),
    ]
