# Generated by Django 5.2.11 on 2026-05-13 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0019_stay_lunch_reminder_reminderlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='accompanying_guest_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
