# Generated by Django 5.2.4 on 2025-07-22 07:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_remove_hotel_admin_remove_hotel_created_at_and_more'),
        ('user', '0002_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_active_hotel_user',
            field=models.BooleanField(default=True),
        ),
    ]
