# Generated by Django 5.2.4 on 2025-07-29 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_created_by_user_hotel_user_is_active_hotel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='resend_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
