# Generated by Django 5.2.5 on 2025-08-25 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('platform_admin', 'Platform Admin'), ('platform_staff', 'Platform Staff'), ('hotel_admin', 'Hotel Admin'), ('manager', 'Manager'), ('receptionist', 'Receptionist'), ('department_staff', 'Department Staff')], max_length=20, null=True),
        ),
    ]
