# Generated by Django 5.2.5 on 2025-10-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('platform_admin', 'Platform Admin'), ('platform_staff', 'Platform Staff'), ('hotel_admin', 'Hotel Admin'), ('manager', 'Manager'), ('receptionist', 'Receptionist'), ('department_staff', 'Department Staff'), ('other_staff', 'Other Staff')], max_length=20, null=True),
        ),
    ]
