# Generated by Django 5.2.5 on 2025-12-14 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='internal_or_external',
            field=models.BooleanField(default=True, help_text='True for internal link, False for external link'),
        ),
        migrations.AddField(
            model_name='notification',
            name='link',
            field=models.URLField(blank=True, help_text='URL to navigate to when notification is clicked', null=True),
        ),
    ]
