# Generated by Django 5.2.5 on 2025-12-14 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_internal_or_external_notification_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='internal_or_external',
        ),
        migrations.AddField(
            model_name='notification',
            name='link_label',
            field=models.CharField(blank=True, help_text='Label text for the link button', max_length=100, null=True),
        ),
    ]
