# Generated by Django 5.2.5 on 2025-12-14 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0023_hotel_google_review_link'),
        ('notifications', '0003_remove_notification_internal_or_external_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='group_type',
            field=models.CharField(blank=True, choices=[('hotel_staff', 'Hotel Staff'), ('platform_user', 'Platform User')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='hotel',
            field=models.ForeignKey(blank=True, help_text='Required for hotel_staff group notifications', null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['group_type', 'hotel'], name='notificatio_group_t_c303c8_idx'),
        ),
    ]
